# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/colbywang/Desktop/A-pex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/colbywang/Desktop/A-pex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/colbywang/Desktop/A-pex/CMakeFiles /Users/colbywang/Desktop/A-pex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/colbywang/Desktop/A-pex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multiobj

# Build rule for target.
multiobj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multiobj
.PHONY : multiobj

# fast build rule for target.
multiobj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/build
.PHONY : multiobj/fast

src/BiCriteria/AbstractSolver.o: src/BiCriteria/AbstractSolver.cpp.o
.PHONY : src/BiCriteria/AbstractSolver.o

# target to build an object file
src/BiCriteria/AbstractSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/AbstractSolver.cpp.o
.PHONY : src/BiCriteria/AbstractSolver.cpp.o

src/BiCriteria/AbstractSolver.i: src/BiCriteria/AbstractSolver.cpp.i
.PHONY : src/BiCriteria/AbstractSolver.i

# target to preprocess a source file
src/BiCriteria/AbstractSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/AbstractSolver.cpp.i
.PHONY : src/BiCriteria/AbstractSolver.cpp.i

src/BiCriteria/AbstractSolver.s: src/BiCriteria/AbstractSolver.cpp.s
.PHONY : src/BiCriteria/AbstractSolver.s

# target to generate assembly for a file
src/BiCriteria/AbstractSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/AbstractSolver.cpp.s
.PHONY : src/BiCriteria/AbstractSolver.cpp.s

src/BiCriteria/ApexSearch.o: src/BiCriteria/ApexSearch.cpp.o
.PHONY : src/BiCriteria/ApexSearch.o

# target to build an object file
src/BiCriteria/ApexSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/ApexSearch.cpp.o
.PHONY : src/BiCriteria/ApexSearch.cpp.o

src/BiCriteria/ApexSearch.i: src/BiCriteria/ApexSearch.cpp.i
.PHONY : src/BiCriteria/ApexSearch.i

# target to preprocess a source file
src/BiCriteria/ApexSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/ApexSearch.cpp.i
.PHONY : src/BiCriteria/ApexSearch.cpp.i

src/BiCriteria/ApexSearch.s: src/BiCriteria/ApexSearch.cpp.s
.PHONY : src/BiCriteria/ApexSearch.s

# target to generate assembly for a file
src/BiCriteria/ApexSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/ApexSearch.cpp.s
.PHONY : src/BiCriteria/ApexSearch.cpp.s

src/BiCriteria/BOAStar.o: src/BiCriteria/BOAStar.cpp.o
.PHONY : src/BiCriteria/BOAStar.o

# target to build an object file
src/BiCriteria/BOAStar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/BOAStar.cpp.o
.PHONY : src/BiCriteria/BOAStar.cpp.o

src/BiCriteria/BOAStar.i: src/BiCriteria/BOAStar.cpp.i
.PHONY : src/BiCriteria/BOAStar.i

# target to preprocess a source file
src/BiCriteria/BOAStar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/BOAStar.cpp.i
.PHONY : src/BiCriteria/BOAStar.cpp.i

src/BiCriteria/BOAStar.s: src/BiCriteria/BOAStar.cpp.s
.PHONY : src/BiCriteria/BOAStar.s

# target to generate assembly for a file
src/BiCriteria/BOAStar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/BOAStar.cpp.s
.PHONY : src/BiCriteria/BOAStar.cpp.s

src/BiCriteria/DominanceChecker.o: src/BiCriteria/DominanceChecker.cpp.o
.PHONY : src/BiCriteria/DominanceChecker.o

# target to build an object file
src/BiCriteria/DominanceChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/DominanceChecker.cpp.o
.PHONY : src/BiCriteria/DominanceChecker.cpp.o

src/BiCriteria/DominanceChecker.i: src/BiCriteria/DominanceChecker.cpp.i
.PHONY : src/BiCriteria/DominanceChecker.i

# target to preprocess a source file
src/BiCriteria/DominanceChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/DominanceChecker.cpp.i
.PHONY : src/BiCriteria/DominanceChecker.cpp.i

src/BiCriteria/DominanceChecker.s: src/BiCriteria/DominanceChecker.cpp.s
.PHONY : src/BiCriteria/DominanceChecker.s

# target to generate assembly for a file
src/BiCriteria/DominanceChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/DominanceChecker.cpp.s
.PHONY : src/BiCriteria/DominanceChecker.cpp.s

src/BiCriteria/NAMOA.o: src/BiCriteria/NAMOA.cpp.o
.PHONY : src/BiCriteria/NAMOA.o

# target to build an object file
src/BiCriteria/NAMOA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/NAMOA.cpp.o
.PHONY : src/BiCriteria/NAMOA.cpp.o

src/BiCriteria/NAMOA.i: src/BiCriteria/NAMOA.cpp.i
.PHONY : src/BiCriteria/NAMOA.i

# target to preprocess a source file
src/BiCriteria/NAMOA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/NAMOA.cpp.i
.PHONY : src/BiCriteria/NAMOA.cpp.i

src/BiCriteria/NAMOA.s: src/BiCriteria/NAMOA.cpp.s
.PHONY : src/BiCriteria/NAMOA.s

# target to generate assembly for a file
src/BiCriteria/NAMOA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/NAMOA.cpp.s
.PHONY : src/BiCriteria/NAMOA.cpp.s

src/BiCriteria/PPA.o: src/BiCriteria/PPA.cpp.o
.PHONY : src/BiCriteria/PPA.o

# target to build an object file
src/BiCriteria/PPA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/PPA.cpp.o
.PHONY : src/BiCriteria/PPA.cpp.o

src/BiCriteria/PPA.i: src/BiCriteria/PPA.cpp.i
.PHONY : src/BiCriteria/PPA.i

# target to preprocess a source file
src/BiCriteria/PPA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/PPA.cpp.i
.PHONY : src/BiCriteria/PPA.cpp.i

src/BiCriteria/PPA.s: src/BiCriteria/PPA.cpp.s
.PHONY : src/BiCriteria/PPA.s

# target to generate assembly for a file
src/BiCriteria/PPA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/PPA.cpp.s
.PHONY : src/BiCriteria/PPA.cpp.s

src/BiCriteria/ShortestPathHeuristic.o: src/BiCriteria/ShortestPathHeuristic.cpp.o
.PHONY : src/BiCriteria/ShortestPathHeuristic.o

# target to build an object file
src/BiCriteria/ShortestPathHeuristic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/ShortestPathHeuristic.cpp.o
.PHONY : src/BiCriteria/ShortestPathHeuristic.cpp.o

src/BiCriteria/ShortestPathHeuristic.i: src/BiCriteria/ShortestPathHeuristic.cpp.i
.PHONY : src/BiCriteria/ShortestPathHeuristic.i

# target to preprocess a source file
src/BiCriteria/ShortestPathHeuristic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/ShortestPathHeuristic.cpp.i
.PHONY : src/BiCriteria/ShortestPathHeuristic.cpp.i

src/BiCriteria/ShortestPathHeuristic.s: src/BiCriteria/ShortestPathHeuristic.cpp.s
.PHONY : src/BiCriteria/ShortestPathHeuristic.s

# target to generate assembly for a file
src/BiCriteria/ShortestPathHeuristic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/ShortestPathHeuristic.cpp.s
.PHONY : src/BiCriteria/ShortestPathHeuristic.cpp.s

src/BiCriteria/SingleCriteria.o: src/BiCriteria/SingleCriteria.cpp.o
.PHONY : src/BiCriteria/SingleCriteria.o

# target to build an object file
src/BiCriteria/SingleCriteria.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/SingleCriteria.cpp.o
.PHONY : src/BiCriteria/SingleCriteria.cpp.o

src/BiCriteria/SingleCriteria.i: src/BiCriteria/SingleCriteria.cpp.i
.PHONY : src/BiCriteria/SingleCriteria.i

# target to preprocess a source file
src/BiCriteria/SingleCriteria.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/SingleCriteria.cpp.i
.PHONY : src/BiCriteria/SingleCriteria.cpp.i

src/BiCriteria/SingleCriteria.s: src/BiCriteria/SingleCriteria.cpp.s
.PHONY : src/BiCriteria/SingleCriteria.s

# target to generate assembly for a file
src/BiCriteria/SingleCriteria.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/BiCriteria/SingleCriteria.cpp.s
.PHONY : src/BiCriteria/SingleCriteria.cpp.s

src/Utils/Definitions.o: src/Utils/Definitions.cpp.o
.PHONY : src/Utils/Definitions.o

# target to build an object file
src/Utils/Definitions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/Definitions.cpp.o
.PHONY : src/Utils/Definitions.cpp.o

src/Utils/Definitions.i: src/Utils/Definitions.cpp.i
.PHONY : src/Utils/Definitions.i

# target to preprocess a source file
src/Utils/Definitions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/Definitions.cpp.i
.PHONY : src/Utils/Definitions.cpp.i

src/Utils/Definitions.s: src/Utils/Definitions.cpp.s
.PHONY : src/Utils/Definitions.s

# target to generate assembly for a file
src/Utils/Definitions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/Definitions.cpp.s
.PHONY : src/Utils/Definitions.cpp.s

src/Utils/IOUtils.o: src/Utils/IOUtils.cpp.o
.PHONY : src/Utils/IOUtils.o

# target to build an object file
src/Utils/IOUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/IOUtils.cpp.o
.PHONY : src/Utils/IOUtils.cpp.o

src/Utils/IOUtils.i: src/Utils/IOUtils.cpp.i
.PHONY : src/Utils/IOUtils.i

# target to preprocess a source file
src/Utils/IOUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/IOUtils.cpp.i
.PHONY : src/Utils/IOUtils.cpp.i

src/Utils/IOUtils.s: src/Utils/IOUtils.cpp.s
.PHONY : src/Utils/IOUtils.s

# target to generate assembly for a file
src/Utils/IOUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/IOUtils.cpp.s
.PHONY : src/Utils/IOUtils.cpp.s

src/Utils/Logger.o: src/Utils/Logger.cpp.o
.PHONY : src/Utils/Logger.o

# target to build an object file
src/Utils/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/Logger.cpp.o
.PHONY : src/Utils/Logger.cpp.o

src/Utils/Logger.i: src/Utils/Logger.cpp.i
.PHONY : src/Utils/Logger.i

# target to preprocess a source file
src/Utils/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/Logger.cpp.i
.PHONY : src/Utils/Logger.cpp.i

src/Utils/Logger.s: src/Utils/Logger.cpp.s
.PHONY : src/Utils/Logger.s

# target to generate assembly for a file
src/Utils/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/Logger.cpp.s
.PHONY : src/Utils/Logger.cpp.s

src/Utils/MapQueue.o: src/Utils/MapQueue.cpp.o
.PHONY : src/Utils/MapQueue.o

# target to build an object file
src/Utils/MapQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/MapQueue.cpp.o
.PHONY : src/Utils/MapQueue.cpp.o

src/Utils/MapQueue.i: src/Utils/MapQueue.cpp.i
.PHONY : src/Utils/MapQueue.i

# target to preprocess a source file
src/Utils/MapQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/MapQueue.cpp.i
.PHONY : src/Utils/MapQueue.cpp.i

src/Utils/MapQueue.s: src/Utils/MapQueue.cpp.s
.PHONY : src/Utils/MapQueue.s

# target to generate assembly for a file
src/Utils/MapQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/MapQueue.cpp.s
.PHONY : src/Utils/MapQueue.cpp.s

src/Utils/apex.o: src/Utils/apex.cpp.o
.PHONY : src/Utils/apex.o

# target to build an object file
src/Utils/apex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/apex.cpp.o
.PHONY : src/Utils/apex.cpp.o

src/Utils/apex.i: src/Utils/apex.cpp.i
.PHONY : src/Utils/apex.i

# target to preprocess a source file
src/Utils/apex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/apex.cpp.i
.PHONY : src/Utils/apex.cpp.i

src/Utils/apex.s: src/Utils/apex.cpp.s
.PHONY : src/Utils/apex.s

# target to generate assembly for a file
src/Utils/apex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/Utils/apex.cpp.s
.PHONY : src/Utils/apex.cpp.s

src/driver.o: src/driver.cpp.o
.PHONY : src/driver.o

# target to build an object file
src/driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/driver.cpp.o
.PHONY : src/driver.cpp.o

src/driver.i: src/driver.cpp.i
.PHONY : src/driver.i

# target to preprocess a source file
src/driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/driver.cpp.i
.PHONY : src/driver.cpp.i

src/driver.s: src/driver.cpp.s
.PHONY : src/driver.s

# target to generate assembly for a file
src/driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multiobj.dir/build.make CMakeFiles/multiobj.dir/src/driver.cpp.s
.PHONY : src/driver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... multiobj"
	@echo "... src/BiCriteria/AbstractSolver.o"
	@echo "... src/BiCriteria/AbstractSolver.i"
	@echo "... src/BiCriteria/AbstractSolver.s"
	@echo "... src/BiCriteria/ApexSearch.o"
	@echo "... src/BiCriteria/ApexSearch.i"
	@echo "... src/BiCriteria/ApexSearch.s"
	@echo "... src/BiCriteria/BOAStar.o"
	@echo "... src/BiCriteria/BOAStar.i"
	@echo "... src/BiCriteria/BOAStar.s"
	@echo "... src/BiCriteria/DominanceChecker.o"
	@echo "... src/BiCriteria/DominanceChecker.i"
	@echo "... src/BiCriteria/DominanceChecker.s"
	@echo "... src/BiCriteria/NAMOA.o"
	@echo "... src/BiCriteria/NAMOA.i"
	@echo "... src/BiCriteria/NAMOA.s"
	@echo "... src/BiCriteria/PPA.o"
	@echo "... src/BiCriteria/PPA.i"
	@echo "... src/BiCriteria/PPA.s"
	@echo "... src/BiCriteria/ShortestPathHeuristic.o"
	@echo "... src/BiCriteria/ShortestPathHeuristic.i"
	@echo "... src/BiCriteria/ShortestPathHeuristic.s"
	@echo "... src/BiCriteria/SingleCriteria.o"
	@echo "... src/BiCriteria/SingleCriteria.i"
	@echo "... src/BiCriteria/SingleCriteria.s"
	@echo "... src/Utils/Definitions.o"
	@echo "... src/Utils/Definitions.i"
	@echo "... src/Utils/Definitions.s"
	@echo "... src/Utils/IOUtils.o"
	@echo "... src/Utils/IOUtils.i"
	@echo "... src/Utils/IOUtils.s"
	@echo "... src/Utils/Logger.o"
	@echo "... src/Utils/Logger.i"
	@echo "... src/Utils/Logger.s"
	@echo "... src/Utils/MapQueue.o"
	@echo "... src/Utils/MapQueue.i"
	@echo "... src/Utils/MapQueue.s"
	@echo "... src/Utils/apex.o"
	@echo "... src/Utils/apex.i"
	@echo "... src/Utils/apex.s"
	@echo "... src/driver.o"
	@echo "... src/driver.i"
	@echo "... src/driver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

